version: 2
variables:
  cache_config: &cache_config
    key: v2-rep-{{ checksum "project.clj" }}-{{ checksum "deps/build.sh" }}
    paths:
      - ~/.m2
jobs:
  build-and-test:
    docker:
      - image: eraserhd/rep:primary
    steps:
      - checkout
      - restore_cache:
          <<: *cache_config
      - run:
          name: Running tests
          command: deps/lein midje
      - save_cache:
          <<: *cache_config
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
