version: 2
variables:
  cache_config: &cache_config
    key: v3-rep-{{ checksum "project.clj" }}
    paths:
      - ~/.m2
jobs:
  build-and-test:
    docker:
      - image: eraserhd/rep:primary
    steps:
      - checkout
      - restore_cache:
          <<: *cache_config
      - run:
          name: Running tests
          command: deps/lein midje
      - run:
          name: Building Linux package
          command: |
            eval "version=$(awk 'NR == 1{print $3}' project.clj)"
            package="rep-$version-linux-amd64"
            deps/lein native-image
            mkdir -p dist/$package/
            cp target/default+uberjar/rep dist/$package/rep
            asciidoctor -b manpage -o dist/$package/rep.1 rep.1.adoc
            ( cd dist && tar czf $package.tar.gz $package/ )
      - store_artifacts:
          path: dist
      - save_cache:
          <<: *cache_config
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
