version: 2
variables:
  cache_config: &cache_config
    key: v2-rep-{{ checksum "project.clj" }}-{{ checksum "deps/build.sh" }}
    paths:
      - deps
      - ~/.m2
jobs:
  build-and-test:
    docker:
      - image: eraserhd/rep:primary
    steps:
      - checkout
      - restore_cache:
          <<: *cache_config
      - run:
          name: Building patched dependencies
          command: |
            if ! [ -f deps/built ]; then
                ./deps/build.sh
                touch deps/built
            fi
      - run:
          name: Running tests
          command: |
            source deps/path.sh
            deps/lein midje
      - save_cache:
          <<: *cache_config
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
