version: 2
variables:
  cache_config: &cache_config
    key: v3-rep-{{ checksum "project.clj" }}
    paths:
      - ~/.m2
jobs:
  linux-build:
    docker:
      - image: eraserhd/rep:primary
    steps:
      - checkout
      - restore_cache:
          <<: *cache_config
      - run:
          name: Running tests
          command: deps/lein midje
      - run:
          name: Building Linux package
          command: |
            eval "version=$(awk 'NR == 1{print $3}' project.clj)"
            package="rep-$version-linux-amd64"
            deps/lein native-image
            mkdir -p pkg/$package/ dist/
            cp target/default+uberjar/rep pkg/$package/rep
            asciidoctor -b manpage -o pkg/$package/rep.1 rep.1.adoc
            ( cd pkg && tar czf ../dist/$package.tar.gz $package/ )
      - store_artifacts:
          path: dist
          destination: /
      - save_cache:
          <<: *cache_config
  macos-build:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - restore_cache:
          <<: *cache_config
      - run:
          name: Running tests
          command: deps/lein midje
      - save_cache:
          <<: *cache_config
workflows:
  version: 2
  build-and-test:
    jobs:
      - linux-build
      - macos-build:
          requires:
            - linux-build
