version: 2
variables:
  cache_config: &cache_config
    key: v2-rep-{{ checksum "project.clj" }}-{{ checksum "deps/build.sh" }}
    paths:
      - deps
      - ~/.m2
jobs:
  build-and-test:
    docker:
      - image: circleci/clojure:lein-2.8.3
    steps:
      - checkout
      - restore_cache:
          <<: *cache_config
      - run:
          name: Building patched dependencies
          command: |
            if ! [ -f deps/built ]; then
                sudo apt-get install -y patch maven
                ./deps/build.sh
                touch deps/built
            fi
      - run:
          name: Running tests
          command: |
            source deps/path.sh
            deps/lein midje
      - run:
          name: Building native image
          command: |
            source deps/path.sh
            deps/lein native-image
      - save_cache:
          <<: *cache_config
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
